doctrine:
  dbal:
    driver: 'pdo_pgsql'
    server_version: '10'
    dbname: '%env(resolve:POSTGRES_DB)%'
    host: '%env(resolve:DB_HOST)%'
    port: '%env(resolve:DB_PORT)%'
    user: '%env(resolve:POSTGRES_USER)%'
    password: '%env(resolve:POSTGRES_PASSWORD)%'
    charset: "UTF8"
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
