version: '3.4'

services:
  php:
    image: php
    build: ./docker/php
    networks:
      - network_nginx
      - network_php
    volumes:
      - ./:/application:rw,cached

  nginx:
    image: nginx
    build: ./docker/nginx
    networks:
      - network_nginx
    volumes:
      - ./public:/application/public:ro
    ports:
      - 8080:80

  db:
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - network_php
    ports:
      - 5432:5432

volumes:
  db-data: {}

networks:
  network_nginx:
    driver: bridge
  network_php:
    driver: bridge
