export const INFO_URL = '/api/admin/info'
export const LOGIN_URL = '/api/admin/login'
export const LOGOUT_URL = '/ajax/logout'

export const FETCH_CATEGORIES_URL = '/api/admin/category'
export const FETCH_CATEGORY_URL = '/api/admin/category/:id'
export const CREATE_CATEGORY_URL = '/api/admin/category/:id'
export const UPDATE_CATEGORY_URL = '/api/admin/category'
export const DELETE_CATEGORY_URL = '/api/admin/category'
export const FETCH_ALL_CATEGORIES = '/api/admin/category/all'

export const FETCH_PROGRAMS_FORMAT_URL = '/api/admin/program-format'
export const FETCH_PROGRAM_FORMAT_URL = '/api/admin/program-format/:id'
export const CREATE_PROGRAM_FORMAT_URL = '/api/admin/program-format'
export const UPDATE_PROGRAM_FORMAT_URL = '/api/admin/program-format'
export const DELETE_PROGRAM_FORMAT_URL = '/api/admin/program-format'

export const FETCH_PROVIDERS_URL = '/api/admin/provider'
export const FETCH_PROVIDER_URL = '/api/admin/provider/:id'
export const CREATE_PROVIDER_URL = '/api/admin/provider'
export const UPDATE_PROVIDER_URL = '/api/admin/provider'
export const DELETE_PROVIDER_URL = '/api/admin/provider'

export const FETCH_ARTICLES_URL = '/api/admin/article'
export const FETCH_ARTICLE_URL = '/api/admin/article/:id'
export const CREATE_ARTICLE_URL = '/api/admin/article'
export const UPDATE_ARTICLE_URL = '/api/admin/article'
export const DELETE_ARTICLE_URL = '/api/admin/article'

export const FETCH_TAGS_URL = '/api/admin/tag'
export const FETCH_TAG_URL = '/api/admin/tag/:id'

export const FETCH_USERS_URL = '/api/admin/user'

export const FETCH_LOCATIONS_URL = '/api/admin/location'
export const FETCH_LOCATION_URL = '/api/admin/location/:id'
export const CREATE_LOCATION_URL = '/api/admin/location'
export const UPDATE_LOCATION_URL = '/api/admin/location'
export const DELETE_LOCATION_URL = '/api/admin/location'
export const FETCH_ALL_LOCATIONS = '/api/admin/location/all'
