parameters:
  site:
    host: '%env(resolve:SITE_HOST)%'
  social.services:
    vk:
      client_id: '%env(resolve:VK_CLIENT_ID)%'
      secret_key: '%env(resolve:VK_SECRET_KEY)%'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Dto,Exception,Entity,Social,Adapter,Messenger,Migrations,Tests,Helpers,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\EventListener\EntityCacheListener:
    tags:
      - { name: doctrine.event_listener, event: onFlush, priority: 100 }
