parameters:
  site:
    host: '%env(resolve:SITE_HOST)%'
  upload_dir: '%kernel.project_dir%/public/upload'
  pdf_tmp_dir: '%kernel.project_dir%/var/tmp'
  replenish_dir: '%kernel.project_dir%/files/replenish'
  social.services:
    vk:
      client_id: '%env(resolve:VK_CLIENT_ID)%'
      secret_key: '%env(resolve:VK_SECRET_KEY)%'
    ok:
      client_id: '%env(resolve:OK_CLIENT_ID)%'
      public_key: '%env(resolve:OK_PUBLIC_KEY)%'
      secret_key: '%env(resolve:OK_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Dto,Exception,Entity,Adapter,Messenger,Migrations,Tests,SearchHelpers,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\EventListener\EntityCacheListener:
    tags:
      - { name: doctrine.event_listener, event: onFlush, priority: 100 }

  App\EventSubscriber\CustomCacheListener:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  App\EventSubscriber\SearchSubscriber:
    tags:
      - { name: doctrine.event_subscriber, connection: default }
